import React, { useState } from 'react';
import './App.css';
import logo from "./assets/logo.png";

const FRONTEND_ORIGIN = 'http://localhost:3001';

function App() {
  const [activeTab, setActiveTab] = useState('text');
  const [textInput, setTextInput] = useState('');
  const [imageFile, setImageFile] = useState(null);
  const [imagePreview, setImagePreview] = useState(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState(null);
  const [dragActive, setDragActive] = useState(false);
  const [sources, setSources] = useState(null);
  const [sourcesLoading, setSourcesLoading] = useState(false);

  const parseGeminiResponse = (text) => {
    const verdictMatch = text.match(/Verdict:\s*(Real|Fake|Suspicious)/i);
    const confidenceMatch = text.match(/Confidence:\s*(\d+)/i);
    const reasonMatch = text.match(/Reason:\s*([\s\S]*?)(?=\nKeyword:|$)/i);

    const verdictRaw = verdictMatch?.[1]?.toLowerCase() || 'suspicious';
    const verdict =
      verdictRaw === 'real' ? 'real' : verdictRaw === 'fake' ? 'fake' : 'suspicious';
    const confidence = confidenceMatch?.[1] || '70';
    const reason = reasonMatch?.[1]?.trim() || text;

    return {
      verdict,
      confidence,
      analysis: {
        aiGenerated: /ai.generated|artificially|generated by ai/i.test(text),
        aiConfidence: confidence,
        credibilityScore:
          verdict === 'real' ? confidence : 100 - parseInt(confidence),
        factCheck: reason,
        indicators: [
          { type: 'Fake News Detected', detected: verdict === 'fake' },
          { type: 'Suspicious Content', detected: verdict === 'suspicious' },
          { type: 'AI Generated Content', detected: /ai.generated/i.test(text) },
        ],
      },
    };
  };
   
  const fetchSources = async (query) => {
    setSourcesLoading(true);
    setSources(null);

   try {
  const res = await fetch(
    `https://trusync-nh1e.vercel.app/sources?q=${encodeURIComponent(query)}`,
    {
      headers: {
        'X-App-Origin': FRONTEND_ORIGIN,
      },
    }
  );
      const data = await res.json();
      setSources(data);
    } catch (err) {
      console.error("Sources error:", err);
      setSources([]);
    }

    setSourcesLoading(false);
  };

  const handleTextAnalysis = async () => {
    if (!textInput.trim()) return;
    setIsAnalyzing(true);
    setResult(null);

    try {
      const res = await fetch('https://trusync-nh1e.vercel.app/analyze', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-App-Origin': FRONTEND_ORIGIN,
        },
        body: JSON.stringify({
          text: textInput,
        }),
      });

      const data = await res.json();
      console.log("Backend response:", data);

      if (!res.ok || !data.result) {
        throw new Error(data.error || "Invalid response from backend");
      }

      setResult(parseGeminiResponse(data.result));
      // ✅ Use Gemini-extracted keyword, fallback to raw input if missing
      fetchSources(data.keyword || textInput);
    } catch (err) {
      console.error('Text analysis error:', err);
      setResult({
        verdict: 'suspicious',
        confidence: '0',
        analysis: {
          aiGenerated: false,
          aiConfidence: '0',
          credibilityScore: '0',
          factCheck: err.message || 'Backend error',
          indicators: [],
        },
      });
    }
    setIsAnalyzing(false);
  };

  const handleImageAnalysis = async () => {
    if (!imageFile) return;
    setIsAnalyzing(true);
    setResult(null);

    try {
      const formData = new FormData();
      formData.append('image', imageFile);

   

      const res = await fetch('https://trusync-nh1e.vercel.app/analyze-image', {
        method: 'POST',
        headers: {
          'X-App-Origin': FRONTEND_ORIGIN,
        },
        body: formData,
      });
      const data = await res.json();
      setResult(parseGeminiResponse(data.result));
      // ✅ Use Gemini-extracted keyword, fallback to generic if missing
      fetchSources(data.keyword || 'misinformation fact check');
    } catch (err) {
      console.error('Image analysis error:', err);
      setResult({
        verdict: 'suspicious',
        confidence: '0',
        analysis: {
          aiGenerated: false,
          aiConfidence: '0',
          credibilityScore: '0',
          factCheck: 'Error connecting to server. Make sure backend is running.',
          indicators: [],
        },
      });
    }

    setIsAnalyzing(false);
  };

  const handleImageUpload = (e) => {
    const file = e.target.files?.[0];
    if (file) {
      setImageFile(file);
      const reader = new FileReader();
      reader.onloadend = () => setImagePreview(reader.result);
      reader.readAsDataURL(file);
      setResult(null);
    }
  };

  const handleDrag = (e) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === 'dragenter' || e.type === 'dragover') setDragActive(true);
    else if (e.type === 'dragleave') setDragActive(false);
  };

  const handleDrop = (e) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      const file = e.dataTransfer.files[0];
      setImageFile(file);
      const reader = new FileReader();
      reader.onloadend = () => setImagePreview(reader.result);
      reader.readAsDataURL(file);
      setResult(null);
    }
  };

  const resetAnalysis = () => {
    setTextInput('');
    setImageFile(null);
    setImagePreview(null);
    setResult(null);
    setSources(null);
  };

  return (
    <div className="app">
     
      <div className="grain-overlay"></div>

      <header className="header">
        <div className="logo-section">
          <img
            src={logo}
            alt="TruSync Logo"
            className="logo"
          />
          <h1 className="logo-text">Trusync</h1>
        </div>
        <p className="tagline">AI-Powered Truth Detection</p>
      </header>

      <main className="main-content">
        <div className="hero-section">
          <h2 className="hero-title">
            Identify Fake News
            <span className="title-accent"> Instantly</span>
          </h2>
          <p className="hero-subtitle">
            Upload text or images to verify authenticity using advanced AI detection
          </p>
        </div>

        <div className="analysis-container">
          <div className="tab-switcher">
            <button
              className={`tab-button ${activeTab === 'text' ? 'active' : ''}`}
              onClick={() => { setActiveTab('text'); resetAnalysis(); }}
            >
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M4 6h16M4 12h16M4 18h16" />
              </svg>
              Text Analysis
            </button>
            <button
              className={`tab-button ${activeTab === 'image' ? 'active' : ''}`}
              onClick={() => { setActiveTab('image'); resetAnalysis(); }}
            >
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <rect x="3" y="3" width="18" height="18" rx="2" />
                <circle cx="8.5" cy="8.5" r="1.5" />
                <path d="M21 15l-5-5L5 21" />
              </svg>
              Image Analysis
            </button>
          </div>

          <div className="input-section">
            {activeTab === 'text' ? (
              <div className="text-input-wrapper">
                <textarea
                  className="text-input"
                  placeholder="Paste news article, headline, or any text content here..."
                  value={textInput}
                  onChange={(e) => setTextInput(e.target.value)}
                  rows={8}
                />
                <div className="input-footer">
                  <span className="char-count">{textInput.length} characters</span>
                  <button
                    className="analyze-btn"
                    onClick={handleTextAnalysis}
                    disabled={!textInput.trim() || isAnalyzing}
                  >
                    {isAnalyzing ? (
                      <><span className="spinner"></span>Analyzing...</>
                    ) : (
                      <>
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                          <path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                        </svg>
                        Analyze Text
                      </>
                    )}
                  </button>
                </div>
              </div>
            ) : (
              <div
                className={`image-upload-wrapper ${dragActive ? 'drag-active' : ''}`}
                onDragEnter={handleDrag}
                onDragLeave={handleDrag}
                onDragOver={handleDrag}
                onDrop={handleDrop}
              >
                {!imagePreview ? (
                  <label className="upload-area">
                    <input type="file" accept="image/*" onChange={handleImageUpload} hidden />
                    <div className="upload-icon">
                      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M17 8l-5-5-5 5M12 3v12" />
                      </svg>
                    </div>
                    <p className="upload-text">Click to upload or drag and drop</p>
                    <p className="upload-hint">PNG, JPG, JPEG up to 10MB</p>
                  </label>
                ) : (
                  <div className="image-preview-wrapper">
                    <img src={imagePreview} alt="Preview" className="image-preview" />
                    <div className="preview-actions">
                      <button className="remove-btn" onClick={resetAnalysis}>
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                          <path d="M18 6L6 18M6 6l12 12" />
                        </svg>
                        Remove
                      </button>
                      <button
                        className="analyze-btn"
                        onClick={handleImageAnalysis}
                        disabled={isAnalyzing}
                      >
                        {isAnalyzing ? (
                          <><span className="spinner"></span>Analyzing...</>
                        ) : (
                          <>
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                              <path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                            </svg>
                            Analyze Image
                          </>
                        )}
                      </button>
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>

          {result && (
            <div className={`result-section ${result.verdict}`}>
              <div className="result-header">
                <div className="verdict-badge">
                  <div className={`verdict-icon ${result.verdict}`}>
                    {result.verdict === 'real' ? (
                      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                        <path d="M20 6L9 17l-5-5" />
                      </svg>
                    ) : (
                      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                        <path d="M18 6L6 18M6 6l12 12" />
                      </svg>
                    )}
                  </div>
                  <div className="verdict-text">
                    <h3 className="verdict-title">
                      {result.verdict === 'real'
                        ? 'Likely Authentic'
                        : result.verdict === 'fake'
                        ? 'Potentially Fake'
                        : 'Suspicious Content'}
                    </h3>
                    <p className="confidence-text">{result.confidence}% Confidence</p>
                  </div>
                </div>
              </div>

              <div className="analysis-details">
                <div className="detail-grid">
                  <div className="detail-card">
                    <div className="detail-label">AI Generated</div>
                    <div className="detail-value">
                      {result.analysis.aiGenerated ? 'Yes' : 'No'}
                      <span className="detail-secondary">
                        ({result.analysis.aiConfidence}% confidence)
                      </span>
                    </div>
                  </div>

                  <div className="detail-card">
                    <div className="detail-label">Credibility Score</div>
                    <div className="detail-value">
                      {result.analysis.credibilityScore}%
                      <div className="progress-bar">
                        <div
                          className="progress-fill"
                          style={{ width: `${result.analysis.credibilityScore}%` }}
                        ></div>
                      </div>
                    </div>
                  </div>

                  <div className="detail-card full-width">
                    <div className="detail-label">Fact Check</div>
                    <div className="detail-value">{result.analysis.factCheck}</div>
                  </div>
                </div>

                <div className="indicators-section">
                  <h4 className="indicators-title">Detection Indicators</h4>
                  <div className="indicators-list">
                    {result.analysis.indicators.map((indicator, index) => (
                      <div key={index} className="indicator-item">
                        <div className={`indicator-status ${indicator.detected ? 'detected' : 'not-detected'}`}>
                          {indicator.detected ? '●' : '○'}
                        </div>
                        <span className="indicator-label">{indicator.type}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              <button className="new-analysis-btn" onClick={resetAnalysis}>
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                </svg>
                New Analysis
              </button>
            </div>
          )}

          {(sourcesLoading || sources) && (
            <div className="sources-section">
              <h4 className="sources-title">Related Sources</h4>
              {sourcesLoading && (
                <div className="sources-loading">
                  <span className="spinner"></span> Fetching sources...
                </div>
              )}
              {sources && sources.length === 0 && (
                <p className="sources-empty">No sources found.</p>
              )}
              {sources && sources.map((src, i) => (
                <a key={i} href={src.url} target="_blank" rel="noreferrer" className="source-card">
                  <span className={`source-badge ${src.type === 'Wikipedia' ? 'badge-wiki' : 'badge-news'}`}>
                    {src.type}
                  </span>
                  <div className="source-body">
                    <p className="source-title">{src.title}</p>
                    <p className="source-snippet">{src.snippet}</p>
                  </div>
                </a>
              ))}
            </div>
          )}

        </div>

        <div className="features-section">
          <div className="feature-card">
            <div className="feature-icon">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
              </svg>
            </div>
            <h3 className="feature-title">AI Detection</h3>
            <p className="feature-desc">Advanced algorithms identify AI-generated content</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <h3 className="feature-title">Fact Verification</h3>
            <p className="feature-desc">Cross-reference claims against trusted sources</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
              </svg>
            </div>
            <h3 className="feature-title">Image Analysis</h3>
            <p className="feature-desc">OCR text extraction and manipulation detection</p>
          </div>
        </div>
      </main>

      <footer className="footer">
        <p>© 2026 Truthify. Powered by AI Technology</p>
      </footer>
    </div>
  );
}

export default App;
